config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show]
  resources :shops
  resources :categories
  get 'home/index'

  get "users/:id" => "users#show"

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  belongs_to :user

  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shops
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :category
  belongs_to :user

   mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

  def after_sign_in_path_for(resource)
    shops_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all.order(created_at: :desc)
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    if @shop.user_id == current_user.id
      respond_to do |format|
        if @shop.update(shop_params)
          format.html { redirect_to shops_path, notice: 'Shop was successfully updated.' }
          format.json { render :show, status: :ok, location: @shop }
        else
          format.html { render :edit }
          format.json { render json: @shop.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @shop, notice: "権限がありません"
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    if @shop.user_id == current_user.name
        @shop.destroy
      msg = "削除しました"
    else
      msg = "権限がありません"
    end
    respond_to do |format|
      format.html { redirect_to shops_url, notice: msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:category_id, :name, :address, :user_id, :content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
     @user = User.find_by(id: params[:id])
  end

  protected

 def configure_account_update_params
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :avatar_cache, :remove_avatar])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %> <%= link_to "Shop", shops_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Lunchmap2</title>

    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch|Nanum+Pen+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch|Nanum+Pen+Script" rel="stylesheet">
    <%= stylesheet_link_tag "home", :media => "all" %>
  </head>

  <body>
    <div class="top">
      <div class="container">
        <div class="top-font">
          <%= link_to shops_path, style: "text-decoration: none;" do%>
            <h1>Gourmet Report</h1>
            <p>Gourmet Reportへようこそ</p>
          <% end %>

        <% if current_user %>
          <%= link_to "お店一覧", shops_path,class: "shops_btn btn btn-info" %>
        <% else %>
          <div class="top-btn">
            <%= link_to "ログイン", new_user_session_path, class: "login btn btn-success" %>
            <%= link_to "新規登録", new_user_registration_path, class: "sign_up btn btn-warning " %>
           </div>
        <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunchmap2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
    <!-- Fixed navbar -->
<nav class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <div class="top-icon">
        <%= link_to root_path, class: "navbar-brand" do %>
          <span class="fa fa-utensils">ぐるリポ</span>
        <% end %>
      </div>
    </div>


      <% if current_user %>
        <p class="navbar-text">ようこそ <%= link_to current_user.name, "/users/#{current_user.id}", style: "color: #9F9F9F;" %> さん。</p>
      <% else %>
          <p class="navbar-text">ようこそ ゲスト さん。</p>
      <% end %>

      <%= link_to 'レポート', new_shop_path, class: "btn btn-warning new-btn" %>

      <div class="nav navbar-nav dropdown nav-btn-r">
        <a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-bars nav-btn"></span></a>
           <ul class="dropdown-menu dropdown-menu-right">
             <li><%= link_to "お店一覧", shops_path %></li>
             <% if current_user %>
               <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
               <li><%= link_to "アカウント編集", edit_user_registration_path %></li>
               <li><%= link_to "プロフィール", "/users/#{current_user.id}" %></li>
              <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <% end %>
            </ul>
        </div>



         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
      <script>
        $('.dropdown-toggle').dropdown()
      </script>

  </div>
</nav>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shops/_form.html.erb
<!DOCTYPE html>
  <head>
    <%= stylesheet_link_tag "shops", :media => "all" %>
  </head>
  <body>
    <%= form_with(model: shop, local: true, html: {class: "form-horizontal", role: "form"}) do |form| %>
      <% if shop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

          <ul>
          <% shop.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>



      <div class="form-group">
        <%= form.label :category_id, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= form.select :category_id, Category.all.map{|o| [o.name, o.id]} %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :name, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= form.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :address, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= form.text_field :address %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :content, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= form.text_area :content, :size=>"50x8" %>
        </div>
      </div>

      <div class="form-group">
        <img id="avatar_img_prev" src="#" class='hidden' />
        <%= form.label :image, class: "col-sm-1 control-label" %>
        <%= image_tag shop.image.to_s, class: 'avatar_present_img' %>
        <%= form.file_field :image, id: 'post_img' %>
      </div>
      <script>
        $( document ).on('turbolinks:load', function() {
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#avatar_img_prev').attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
        }
      }

      $("#post_img").change(function(){
        $('#avatar_img_prev').removeClass('hidden');
        $('.avatar_present_img').remove();
        readURL(this);
      });
    });
      </script>

      <div class="actions">
        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-12">
            <%= form.submit "投稿", class: "btn btn-success"%>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>


<%= link_to 'Back', shops_path, class: "btn btn-default" %>

app/views/shops/index.html.erb
<!DOCTYPE html>
  <head>
    <%= stylesheet_link_tag "shops", :media => "all" %>
  </head>
  <body>
    <div class="shop-flame">
      <div class="container">
        <% @shops.each do |shop| %>
          <%= link_to shop, style: "text-decoration: none;" do %>
          <div class="shop-list">
            <span class="fa fa-utensils"></span>
              <div class="shop-name">
                <%= shop.name %>
              </div>
              <div class="temporary">
                <%= shop.category.name%>/
                <%= shop.address %>
              </div>
              <div class="time">
                <%= l shop.created_at, format: :short %>
              </div>

              <div class="borderline">
              </div>
              <div class="image">
                <%= image_tag shop.image.to_s %>
              </div>
              <div class="content">
                <%= shop.content %>
              </div>
              <div class="icon">
                <object><%= link_to "/users/#{shop.user.id}" do %>
                  <% if shop.user.persisted? && shop.user.avatar? %>
                    <%= image_tag shop.user.avatar.to_s %>
                  <% else %>
                      <%= image_tag "/icon.jpg" %>
                  <% end %>
                <% end %></object>
              </div>
              <div class="name">
                <object><%= link_to shop.user.name, "/users/#{shop.user.id}", :style=>"color: black;" %></object>
              </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <br>

    
  </body>
</html>

app/views/shops/index2.html.erb
<h1>Shops</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Store</th>
      <th>Address</th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.user.name, shop, class: "widelink" %></td>
        <td><%= link_to shop.category.name, shop, class: "widelink" %></td>
        <td><%= link_to shop.name, shop, class: "widelink" %></td>
        <td><%= link_to shop.address, shop, class: "widelink" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path, class: "btn btn-primary" %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @shop.user.name %>
</p>

<p>
  <strong>Store:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shop.category.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>Content:</strong>
  <%= @shop.content %>
</p>

<%= content_tag(:iframe,
 'map',
  src:'https://www.google.com/maps/embed/v1/place?q=@shop.address&key=AIzaSyBpPMiU4cysQDdFRpel020GXSIxvlQfLws',
   width: "100%",
    height: 360,
     frameborder: 0) %>

<br>
<%= link_to 'Back', shops_path, class: "btn btn-default" %>
<% if user_signed_in? && @shop.user_id == current_user.id %>
  <%= link_to 'Edit', edit_shop_path(@shop), class: "btn btn-success" %>
  <%= link_to "削除",@shop, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger"  %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
  <head>
    <%= stylesheet_link_tag "users.css", :media => "all" %>
  </head>
  <body>
    <div class="profile">
      <div class="container">
        <div class="profile-avatar">
          <% if @user.persisted? && @user.avatar? %>
            <%= image_tag @user.avatar.to_s %>
          <% else %>
            <%= image_tag "/icon.jpg" %>
          <% end %>
        </div>
        <div class="profile-text">
          <h3><%= @user.name %></h3>
        </div>
      </div>
    </div>
  </body>
</html>